import { Component, ElementRef, EventEmitter, Inject, Input, OnInit, Output, ViewChild } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { CassavaAreaServiceService } from '../cassava-area-service.service';
import { MAT_DIALOG_DATA, MatDialogRef } from '@angular/material/dialog';
import { take } from 'rxjs';
import Swal from 'sweetalert2';
import { MapGeocoder } from '@angular/google-maps';
import { HttpClient } from '@angular/common/http';
import * as turf from '@turf/turf';

@Component({
  selector: 'app-edit-planted',
  templateUrl: './edit-planted.component.html',
  styleUrls: ['./edit-planted.component.css']
})

export class EditPlantedComponent implements OnInit {
  @Output() closeForm = new EventEmitter<void>();
  @Input() plot_id!: number; 
  @ViewChild('mapContainer', { static: false }) mapContainer!: ElementRef;
  autoGeneratedName: string = '';
  plantedAreaForm!: FormGroup;
  mapCenter = { lat: 13.7563, lng: 100.5018 };  // ค่าเริ่มต้นของศูนย์กลางแผนที่
  zoom = 10;
  polygonCoords: google.maps.LatLngLiteral[] = [];
  polygonOptions: google.maps.PolygonOptions = {
    editable: true,
    draggable: true,
    fillColor: 'red',
    fillOpacity: 0.3,
    strokeColor: 'red',
    strokeOpacity: 0.8,
    strokeWeight: 2,
  };
  isDragging = false;
  currentLocationMarker: google.maps.LatLngLiteral | null = null;
  areaInRai = 0;
  areaInNgan = 0;
  markers: google.maps.Marker[] = [];
  userId: string = '';

  existingPlotNames: string[] = [];
  areaText = '0 ไร่ 0 ตารางวา';
  map!: google.maps.Map;
  private staticMapsApiUrl = 'https://maps.googleapis.com/maps/api/staticmap';

  constructor(
    private fb: FormBuilder,
    private route: ActivatedRoute,
    private plantedAreaService: CassavaAreaServiceService,
    private geocoder: MapGeocoder,
    private http: HttpClient,
  ) { }

  ngOnInit(): void {
    if (!this.plot_id) {
        console.error('❌ plot_id is not provided!');
        this.showErrorAlert('ไม่พบข้อมูลแปลงที่ต้องการแก้ไข');
        return;
    }

    this.userId = localStorage.getItem('userId') || '';
    this.initForm();
    this.loadPlotData();
  }

  initForm(): void {
    this.plantedAreaForm = this.fb.group({
      plot_name: ['', Validators.required],
      area_rai: ['', Validators.required],
      searchQuery: ['']
    });
  }

  loadPlotData(): void {
    debugger
    if (!this.plot_id) return;

    this.plantedAreaService.getPlotById(this.plot_id).pipe(take(1)).subscribe({
      next: (data) => {
        if (!data) {
          this.showErrorAlert('ไม่พบข้อมูลแปลง');
          return;
        }

        console.log("📌 API Data Received:", data);

        this.plantedAreaForm.patchValue({
            plot_name: data.plot_name,
            area_rai: data.total_area 
        });

        // ✅ ตรวจสอบประเภทก่อน `split()`
        const latitudes = typeof data.latitudes === "string" ? data.latitudes.split(',') : data.latitudes;
        const longitudes = typeof data.longitudes === "string" ? data.longitudes.split(',') : data.longitudes;
       

        if (!latitudes || !longitudes || latitudes.length !== longitudes.length || latitudes.length === 0) {
          this.showErrorAlert("ไม่มีพิกัดของแปลงนี้");
          return;
        }

        // ✅ ลบค่าที่ผิดพลาด (NaN)
        this.polygonCoords = latitudes.map((lat: string, index: number) => {
          const latParsed = parseFloat(lat);
          const lngParsed = parseFloat(longitudes[index]);
          return isNaN(latParsed) || isNaN(lngParsed) ? null : { lat: latParsed, lng: lngParsed };
        }).filter(Boolean);

        console.log("📌 Final Polygon Coordinates:", this.polygonCoords);

      

        // ✅ อัปเดตศูนย์กลางแผนที่
        setTimeout(() => {
          this.setMapCenter();
          this.updateMarkersOnMap();
        }, 500);

      },
      error: () => {
        this.showErrorAlert("เกิดข้อผิดพลาดในการโหลดข้อมูลแปลง");
      },
    });
}


  updateMarkersOnMap(): void {
    // ลบ markers เก่าก่อนที่จะเพิ่มใหม่
    this.markers.forEach(marker => marker.setMap(null));
    this.markers = [];

    // สร้าง marker สำหรับแต่ละพิกัด
    this.polygonCoords.forEach(coord => {
      const marker = new google.maps.Marker({
        position: coord,
        map: this.map, // ใช้ map ที่ประกาศไว้
        title: 'Plot Location'
      });
      this.markers.push(marker);
      console.log("📍 Marker added at:", coord.lat, coord.lng, "Map:", this.map);
    });
  }
  onSearchPlace(): void {
    const searchQuery = this.plantedAreaForm.get('searchQuery')?.value;

    if (!searchQuery) {
      this.showErrorAlert('โปรดระบุที่อยู่ในการค้นหา');
      return;
    }

    this.geocoder.geocode({ address: searchQuery }).subscribe((result) => {
      if (result.results.length > 0) {
        this.mapCenter = result.results[0].geometry.location.toJSON();
        this.zoom = 15;
        // this.updateMap(); // อัปเดตตำแหน่งแผนที่
      } else {
        this.showErrorAlert('ไม่พบสถานที่ตามที่ค้นหา');
      }
    }, error => {
      console.error('Error during geocoding:', error);
      this.showErrorAlert('เกิดข้อผิดพลาดในการค้นหา');
    });
  }

  setMapCenter(): void {
    if (this.polygonCoords.length > 0) {
        const latitudes = this.polygonCoords.map(coord => coord.lat);
        const longitudes = this.polygonCoords.map(coord => coord.lng);

        const centerLat = latitudes.reduce((sum, lat) => sum + lat, 0) / latitudes.length;
        const centerLng = longitudes.reduce((sum, lng) => sum + lng, 0) / longitudes.length;

        this.mapCenter = { lat: centerLat, lng: centerLng };
        this.zoom = 16;

        if (this.map) {
            this.map.setCenter(this.mapCenter);
        }
    }
  }


  calculateArea(): void {
    if (this.polygonCoords.length < 3) {
      this.areaInRai = 0;
      this.areaText = "0 ไร่ 0 ตารางวา";
      return;
    }
  
    // ปิด Polygon โดยเพิ่มจุดแรกเป็นจุดสุดท้าย
    const closedPolygonCoords = [...this.polygonCoords, this.polygonCoords[0]];
  
    // สร้าง GeoJSON Polygon
    const polygonGeoJSON = turf.polygon([closedPolygonCoords.map(coord => [coord.lng, coord.lat])]);
  
    // คำนวณพื้นที่เป็นตารางเมตร
    const areaInSquareMeters = turf.area(polygonGeoJSON);
  
    // แปลง ตารางเมตร -> ตารางวา -> ไร่-ตารางวา
    const areaInSquareWah = areaInSquareMeters / 4;
    const areaInRai = Math.floor(areaInSquareWah / 400);
    const remainingWah = Math.round(areaInSquareWah % 400);
  
    this.areaInRai = areaInRai;
    this.areaText = `${this.areaInRai} ไร่ ${remainingWah} ตารางวา`;
  
    this.plantedAreaForm.get('area_rai')?.setValue(this.areaText);
  }

  
  

  onClearPolygon(): void {
    this.polygonCoords = [];
    this.currentLocationMarker = null;
    this.areaInRai = 0;
    this.areaInNgan = 0;
    this.markers = [];
  }

  onCurrentLocation(): void {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          this.mapCenter = {
            lat: position.coords.latitude,
            lng: position.coords.longitude
          };
          this.zoom = 15;
          // this.updateMap(); // อัปเดตตำแหน่งแผนที่
        },
        (error) => {
          console.error('Error getting current location', error);
          this.showErrorAlert('ไม่สามารถระบุตำแหน่งปัจจุบันได้');
        }
      );
    } else {
      this.showErrorAlert('เบราว์เซอร์ของคุณไม่รองรับการระบุตำแหน่ง');
    }
  }

  onDragStart(): void {
    this.isDragging = true;
  }
  onDragEnd(): void {
    this.isDragging = false;
  }
  onPolygonEdit(event: google.maps.MapMouseEvent): void {
    const path = event.latLng;
    if (path) {
      this.polygonCoords = [...this.polygonCoords, path.toJSON()];
      this.calculateArea();
    }
  }

  // ฟังก์ชันสำหรับการบันทึกข้อมูล
  onSubmit(): void {
    // ✅ ตรวจสอบว่าฟอร์มถูกต้อง
    if (this.plantedAreaForm.invalid) {
      this.showErrorAlert('กรุณากรอกข้อมูลให้ครบถ้วน');
      return;
    }

    // ✅ ตรวจสอบค่าที่จำเป็น
    if (!this.plot_id || !this.userId) {
      console.error('❌ plot_id หรือ userId ไม่มีค่า');
      this.showErrorAlert('ไม่สามารถบันทึกข้อมูลได้: ไม่มี plot_id หรือ userId');
      return;
    }

    if (!this.polygonCoords || this.polygonCoords.length < 3) {
      console.warn('⚠️ ไม่มีพิกัดหรือพิกัดไม่ครบ');
      this.showErrorAlert('กรุณาระบุพิกัดของแปลงให้ครบถ้วน');
      return;
    }

    // ✅ เตรียมข้อมูลสำหรับการบันทึก
    const formData = this.plantedAreaForm.value;
    const plotName = formData.plot_name;
    const areaRai = this.areaInRai;

    // ✅ แปลงพิกัดให้เป็น LatLng[]
    const polygonLatLngs = this.polygonCoords.map(coord => new google.maps.LatLng(coord.lat, coord.lng));

    console.log('📌 Preparing to save plot data:', {
      plot_id: this.plot_id,
      user_id: this.userId,
      plot_name: plotName,
      area_rai: areaRai,
      latlngs: this.polygonCoords,
    });

    // ✅ เรียกใช้ captureMapImage เพื่อดึงภาพแผนที่
    this.captureMapImage(polygonLatLngs).then((imageUrl) => {
      if (!imageUrl) {
        console.error('❌ ไม่สามารถดึงภาพแผนที่ได้');
        this.showErrorAlert('เกิดข้อผิดพลาดในการดึงภาพแผนที่');
        return;
      }

      // ✅ สร้างข้อมูลที่จะส่งไปยัง API
      const plotData = {
        plot_id: this.plot_id,
        user_id: this.userId,
        plot_name: plotName,
        latlngs: this.polygonCoords,
        fileData: imageUrl,
      };

      console.log('📌 Sending data to API:', plotData);

      // ✅ ส่งข้อมูลไปที่ API
      this.plantedAreaService.updatePlot(plotData).pipe(take(1)).subscribe({
        next: () => {
          Swal.fire({
            icon: 'success',
            title: 'บันทึกข้อมูลสำเร็จ',
            text: 'ข้อมูลแปลงถูกอัปเดตเรียบร้อยแล้ว'
          });
          this.closeForm.emit();
        },
        error: (err) => {
          console.error('❌ Error updating plot:', err);
          this.showErrorAlert('ไม่สามารถบันทึกข้อมูลได้ กรุณาลองใหม่');
        }
      });

    }).catch((error) => {
      console.error('❌ Error capturing map image:', error);
      this.showErrorAlert('ไม่สามารถจับภาพแผนที่ได้');
    });
}

  
  
  
  // ฟังก์ชันสำหรับดึง Base64 ของรูปภาพ
  private captureMapImage(polygonCoords: google.maps.LatLng[]): Promise<string> {
    // คำนวณค่ากึ่งกลางของพอลิกอน
    const center = this.calculatePolygonCenter(polygonCoords);
  
    const lat = center.lat();
    const lng = center.lng();
    const zoom = this.zoom;
    const imageSize = '1024x1024';
    const mapType = 'satellite';
    const scale = 2;
  
    // เพิ่มจุดแรกในตำแหน่งสุดท้ายของพิกัดเพื่อให้เส้นเชื่อมจุดสุดท้ายกับจุดแรก
    const closedPolygonCoords = [...polygonCoords, polygonCoords[0]];
  
    // แปลงพิกัดของพอลิกอนเป็นรูปแบบสตริงสำหรับการร้องขอ API
    const polygonPath = closedPolygonCoords.map(coord => `${coord.lat()},${coord.lng()}`).join('|');
  
    // สร้าง URL ของภาพแผนที่ที่รวมพอลิกอน
    const mapImageUrl = `${this.staticMapsApiUrl}?center=${lat},${lng}&zoom=${zoom}&size=${imageSize}&maptype=${mapType}&scale=${scale}&path=color:0xFF0000%7Cweight:2%7C${polygonPath}&key=AIzaSyDF81bGnOY5TKIXzqN2wfWhTMZXMooP7LY&callback=initMap`;
  
    console.log('Map image URL:', mapImageUrl);
  
    return new Promise((resolve, reject) => {
      this.http.get(mapImageUrl, { responseType: 'blob' }).subscribe(
        (blob: Blob) => {
          const reader = new FileReader();
          reader.onloadend = () => {
            const base64data = (reader.result as string).split(',')[1];
            resolve(`data:image/png;base64,${base64data}`);
          };
          reader.readAsDataURL(blob);
        },
        error => {
          console.error('Error fetching map image:', error);
          reject('ไม่สามารถจับภาพแผนที่ได้');
        }
      );
    });
  }
  private calculatePolygonCenter(polygonCoords: google.maps.LatLng[]): google.maps.LatLng {
    let sumLat = 0;
    let sumLng = 0;
  
    // คำนวณผลรวมของละติจูดและลองจิจูดทั้งหมด
    polygonCoords.forEach(coord => {
      sumLat += coord.lat();
      sumLng += coord.lng();
    });
  
    // คำนวณค่าเฉลี่ยของละติจูดและลองจิจูด
    const centerLat = sumLat / polygonCoords.length;
    const centerLng = sumLng / polygonCoords.length;
  
    // คืนค่าจุดกึ่งกลางในรูปแบบ LatLng
    return new google.maps.LatLng(centerLat, centerLng);
  }
  private showErrorAlert(message: string): void {
    Swal.fire({
      icon: 'error',
      title: 'เกิดข้อผิดพลาด',
      text: message
    });
  }
}
